services:
  - type: web
    name: fermier-pro-ai-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/main.py
    envVars:
      - key: PORT
        sync: false
      - key: BACKEND_API_URL
        sync: false


